### ISSUE TITLE
Password field

### ISSUE THREAD

**Issue by kdebowski** [encode/typesystem#54]
What do you think about this kind of field? 
I was thinking about expanding String type as a first option: 

`typesystem.String(format='password')`

or adding new kind of field `typesystem.Password`

Both options will ensure to create "password" type of input with hidden value. 
The latter would have some additional options of allowed characters (password policy), ie.:

```python
password = typesystem.Password(
    min_length: int,
    require_digit: boolean,
    require_lowercase: boolean,
    require_uppercase: boolean,
    require_non_alphanumeric: boolean
)
```

**Comment by tomchristie** [comment]
Absolutely yes - `String(format="password")` will already function like this as of https://github.com/encode/typesystem/pull/39 but I think having `Password` and `Email` options would both be good.

I'm not sure exactly what we should do about validators on the password field - we should treat that as a separate issue to getting the field type itself in. (Also you probably only want to validate them for complexity on *creating* new passwords, not during actual sign-in attempts.)

The other thing I'd considered here is that we *could* have password fields return the *hashed* value, rather than the raw value. That way around you don't really ever see the raw value itself inside application code, which minimizes the potential space for leaking information.

**Comment by kdebowski** [comment]
Of course, you're right, I meant password validation during creating (like register form). But there is probaby no problem here as you can use two different forms for registering and loggin:

```python

class LoginForm(typesystem.Schema):
    username = typesystem.String()
    password = typesystem.Password()

class RegisterForm(typesystem.Schema):
    username = typesystem.String()
    password1 = typesystem.Password(**password policy here**)
    password2 = typesystem.Password(**password policy here**)
```

this way, during signing in, no validation will happen on password field.

Returning hashed value doesn't sound bad, but there should be some possibility to pass hashing algorithm with it's settings (salt, secret, hashing rounds etc.).

**Comment by tomchristie** [comment]
I think the sensible thing to do would be just to start with introducing a `Password()` field that is exactly implemented as just `String(format="password")`.

We can then do the same for `Email` too. (And later look at if there are any password-specific validations we'd like to support)
